### ISSUE TITLE
大神你好 关于oauth的问题想问下

### ISSUE THREAD

**Issue by fangzehua911** [zhangxd1989/spring-boot-cloud#1]
大神 按照github上的实例我搭建成功了，最后卡在了oauth认证这里，
我部分程序在跑在winods上面，使用postman调用的话如何使用
curl -X POST -vu client:secret http://localhost:8060/uaa/oauth/token -H "Accept: application/json" -d "password=password&username=anil&grant_type=password&scope=read%20write"
我理解为
{
 
  "password": "password",
  "username": "anil",
  "grant_type": "password",
  "scope": "read"
}
但是返回都是
{
  "timestamp": 1496748152926,
  "status": 401,
  "error": "Unauthorized",
  "message": "Full authentication is required to access this resource",
  "path": "/uaa/oauth/token"
}
请问我该如何做，可以留下你的联系方式吗QQ 邮箱之类的

**Comment by fangzehua911** [comment]
问题解决了。感谢，我本地安装了curl工具

**Comment by zhangxd1989** [comment]
@fangzehua911 Postman之类的工具也一样的，这几个认证请求都是基于Basic认证的，Header中传递
Authorization: Basic Y2xpZW50OnNlY3JldA== 就可以，其中秘钥是通过Base64.encode("client:secret") 生成的
