### ISSUE TITLE
auth-service在admin里状态一直都是down

### ISSUE THREAD

**Issue by Rebellioncry** [zhangxd1989/spring-boot-cloud#16]
查找了发现原因是auth-service的health地址监听错了，但是代码完全是按照博主的写的，不知博主是怎么让它变成up的？这个是不是和自定义了eureka的health地址有关？
我在admin里右上角显示auth-service的health地址是
http://xxx:5000/mgmt/uaa/mgmt/health，多了一个mgmt，但不知道配置错在哪里，而直接访问
http://xxx:5000/uaa/mgmt/health是可以返回health信息的，这是什么原因？求解！

**Comment by Rebellioncry** [comment]
找到问题所在了，虽然我用的代码和博主的一样，但是我springboot和spring cloud以及springbootadmin的版本都是使用最新版本的，所以出现问题，博主的代码是没问题的。
现总结如下：
1.springboot可以使用最新版本，即1.5.10
2.spring cloud Edgware.SR1和springbootadmin 1.5.7版本冲突，可能和Edgware.SR1版本大更新有关。
3.都使用最新版的但依照博主的配置的话，auth-service会由于自定义/health路径导致springbootadmin始终读取/health路径出错，所以状态一直是“DOWN”.
希望新来的人可以从这获得一点提示，也希望博主更新一下新版本的配置，谢谢！

**Comment by zsjnb** [comment]
> 查找了发现原因是auth-service的health地址监听错了，但是代码完全是按照博主的写的，不知博主是怎么让它变成up的？这个是不是和自定义了eureka的health地址有关？
> 我在admin里右上角显示auth-service的health地址是
> [http://xxx:5000/mgmt/uaa/mgmt/health，多了一个mgmt，但不知道配置错在哪里，而直接访问](http://xxx:5000/mgmt/uaa/mgmt/health%EF%BC%8C%E5%A4%9A%E4%BA%86%E4%B8%80%E4%B8%AAmgmt%EF%BC%8C%E4%BD%86%E4%B8%8D%E7%9F%A5%E9%81%93%E9%85%8D%E7%BD%AE%E9%94%99%E5%9C%A8%E5%93%AA%E9%87%8C%EF%BC%8C%E8%80%8C%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE)
> [http://xxx:5000/uaa/mgmt/health是可以返回health信息的，这是什么原因？求解！](http://xxx:5000/uaa/mgmt/health%E6%98%AF%E5%8F%AF%E4%BB%A5%E8%BF%94%E5%9B%9Ehealth%E4%BF%A1%E6%81%AF%E7%9A%84%EF%BC%8C%E8%BF%99%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0%EF%BC%9F%E6%B1%82%E8%A7%A3%EF%BC%81)

![image](https://user-images.githubusercontent.com/33953490/51104510-4ad57000-1821-11e9-9f79-077ae1f1cf62.png)
