### ISSUE TITLE
完成了升级 Spring Boot ( 2.0.6.RELEASE ) 和 Spring Cloud ( Finchley.SR2 )

### ISSUE THREAD

**Issue by chanson-chan** [zhangxd1989/spring-boot-cloud#24]
作者似乎不更新了, 我对本项目进行了版本升级和对应的适配修改, [具体请见我的repo](https://github.com/chenchensheng/spring-boot-cloud) 欢迎大家帮忙优化

**Comment by msgi** [comment]
建议直接新起一个repo

**Comment by msgi** [comment]
而且可以升级到2.0.9和SR3了

**Comment by heppytt** [comment]
@陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)

**Comment by chanson-chan** [comment]
> @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)

项目的 README 里有讲呀

**Comment by heppytt** [comment]
> > @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> > ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> > ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)
> 
> 项目的 README 里有讲呀

访问http://localhost:8761/ 访问不到服务。
![image](https://user-images.githubusercontent.com/17058423/59415245-ac603180-8df5-11e9-9519-2e263a71149d.png)

**Comment by chanson-chan** [comment]
> > > @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> > > ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> > > ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)
> > 
> > 
> > 项目的 README 里有讲呀
> 
> 访问http://localhost:8761/ 访问不到服务。
> ![image](https://user-images.githubusercontent.com/17058423/59415245-ac603180-8df5-11e9-9519-2e263a71149d.png)

那 8040 能访问吗, 你可以到我项目里提个 issue

**Comment by heppytt** [comment]
> > > > @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> > > > ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> > > > ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)
> > > 
> > > 
> > > 项目的 README 里有讲呀
> > 
> > 
> > 访问http://localhost:8761/ 访问不到服务。
> > ![image](https://user-images.githubusercontent.com/17058423/59415245-ac603180-8df5-11e9-9519-2e263a71149d.png)
> 
> 那 8040 能访问吗, 你可以到我项目里提个 issue

你好8040也不行和上面一样。 我在你那个里面看不见 issuse

**Comment by chanson-chan** [comment]
> > > > > @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> > > > > ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> > > > > ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)
> > > > 
> > > > 
> > > > 项目的 README 里有讲呀
> > > 
> > > 
> > > 访问http://localhost:8761/ 访问不到服务。
> > > ![image](https://user-images.githubusercontent.com/17058423/59415245-ac603180-8df5-11e9-9519-2e263a71149d.png)
> > 
> > 
> > 那 8040 能访问吗, 你可以到我项目里提个 issue
> 
> 你好8040也不行和上面一样。 我在你那个里面看不见 issuse

哎呀抱歉之前没开, 现在有了, 你可以先试下接口看看是不是正常的
```bash
curl -X POST -vu client:secret http://localhost:8060/uaa/oauth/token -H "Accept: application/json" -d "password=password&username=anil&grant_type=password&scope=read%20write"
```

**Comment by heppytt** [comment]
> > > > > > @陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。
> > > > > > ![image](https://user-images.githubusercontent.com/17058423/59408355-75ceea80-8de6-11e9-9883-10029d99e6f6.png)
> > > > > > ![image](https://user-images.githubusercontent.com/17058423/59408386-85e6ca00-8de6-11e9-99ab-fa84adbaa9df.png)
> > > > > 
> > > > > 
> > > > > 项目的 README 里有讲呀
> > > > 
> > > > 
> > > > 访问http://localhost:8761/ 访问不到服务。
> > > > ![image](https://user-images.githubusercontent.com/17058423/59415245-ac603180-8df5-11e9-9519-2e263a71149d.png)
> > > 
> > > 
> > > 那 8040 能访问吗, 你可以到我项目里提个 issue
> > 
> > 
> > 你好8040也不行和上面一样。 我在你那个里面看不见 issuse
> 
> 哎呀抱歉之前没开, 现在有了, 你可以先试下接口看看是不是正常的
> 
> ```shell
> curl -X POST -vu client:secret http://localhost:8060/uaa/oauth/token -H "Accept: application/json" -d "password=password&username=anil&grant_type=password&scope=read%20write"
> ```

你好啊。我在你那边写了一个问题。放不放面留个联系方式或者见一个群啊。

**Comment by Siwanper** [comment]
${REGISTRY_SERVER_PASSWORD:password}，这个变量是在什么地方配置的，怎么找不到

**Comment by chanson-chan** [comment]
> ${REGISTRY_SERVER_PASSWORD:password}，这个变量是在什么地方配置的，怎么找不到

在 REGISTRY 服务的配置文件里配

**Comment by Siwanper** [comment]
配置了config以后，docker启动service报错No instances found of configserver (config)，然后就Fetching config from server at : http://localhost:8888，我config的端口不是8888.不知道怎么回事
